clusterName: "lab-cluster"
region: "us-east-1"
vpcId: "vpc-0ff6c8b10ae174007"
serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::250566739804:role/aws-load-balancer-controller-lab"
