clusterName: "lab-cluster"
region: "us-east-1"
vpcId: "vpc-01f0bf4b64e6d5d22"
serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::250566739804:role/aws-load-balancer-controller-lab"
