global:
  postgresqlSecretName: "dagster-postgresql-secret"

generatePostgresqlPasswordSecret: false

serviceAccount:
  create: true
  name: "dagster"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::250566739804:role/dagster-role-lab"

ingress:
  enabled: true
  ingressClassName: "alb"
  annotations:
    alb.ingress.kubernetes.io/group.name: "lab-public-alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:250566739804:certificate/099a0bd7-ed1f-49e8-a1b7-b047dc00b417"
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-session-timeout: '3600'
    alb.ingress.kubernetes.io/auth-session-cookie: 'AWSELBAuthSessionCookie'
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn":"arn:aws:cognito-idp:us-east-1:250566739804:userpool/us-east-1_1jMnSnm0C","UserPoolClientId":"2ilke9kdbc613mdeg3hcso2258","UserPoolDomain":"dagster-tjrohweder"}'

  dagsterWebserver:
    host: "dagster.tjrohweder.com"
    path: "/"
    pathType: Prefix

postgresql:
  enabled: false
  postgresqlHost: "lab.cs0qvb1gthx8.us-east-1.rds.amazonaws.com"
  postgresqlUsername: "db_admin"
  postgresqlDatabase: "main"
  postgresqlPort: 5432
  postgresqlPasswordSecret: "dagster-postgresql-secret"

computeLogManager:
  type: S3ComputeLogManager
  config:
    s3ComputeLogManager:
      bucket: "lab-dagster-storage-250566739804"
      prefix: "logs/"

dagsterWebserver:
  env:
    - name: DAGSTER_S3_BUCKET
      value: "lab-dagster-storage-250566739804"
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "rds-secret-provider"
  volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true

dagsterDaemon:
  enabled: true
  runCoordinator:
    enabled: true
    type: QueuedRunCoordinator
    config:
      queuedRunCoordinator:
        maxConcurrentRuns: 10
  env:
    - name: DAGSTER_S3_BUCKET
      value: "lab-dagster-storage-250566739804"
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "rds-secret-provider"
  volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      envVars:
        - "DAGSTER_S3_BUCKET=lab-dagster-storage-250566739804"
      runK8sConfig:
        podSpecConfig:
          serviceAccountName: "dagster"
          nodeSelector:
            karpenter.k8s.aws/instance-cpu-manufacturer: amd
          tolerations:
            - key: workload
              operator: Equal
              value: dagster
              effect: NoSchedule
          initContainers:
            - name: wait-for-dns
              image: debian:bullseye-slim
              command:
                - 'sh'
                - '-c'
                - 'apt-get update && apt-get install -y dnsutils && until nslookup lab.cs0qvb1gthx8.us-east-1.rds.amazonaws.com; do echo "Aguardando rede..."; sleep 2; done'

dagster-user-deployments:
  enabled: true
  deployments:
    - name: "dummy-pipeline"
      image:
        repository: "250566739804.dkr.ecr.us-east-1.amazonaws.com/dagster-dummy-pipeline-lab"
        tag: "latest"
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/opt/dagster/app/repo.py"
      port: 3030
      env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: SNS_ALERTS_TOPIC_ARN
          value: "arn:aws:sns:us-east-1:250566739804:dagster-alerts-lab"
