serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::250566739804:role/karpenter-controller-lab"
settings:
  aws:
    clusterName: "lab-cluster"
    defaultInstanceProfile: "KarpenterNodeProfile-lab-cluster"
