apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rds-secret-provider
  namespace: dagster
spec:
  provider: aws
  secretObjects:
    - secretName: dagster-postgresql-secret
      type: Opaque
      data:
        - objectName: postgresql-password
          key: postgresql-password
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:250566739804:secret:rds!db-ba65931d-94cc-4fcc-b6e3-6cef9898795a-ZB6bvq"
        objectType: "secretsmanager"
        jmesPath:
            - path: "password"
              objectAlias: "postgresql-password"
