apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rds-secret-provider
  namespace: dagster
spec:
  provider: aws
  secretObjects:
    - secretName: dagster-postgresql-secret
      type: Opaque
      data:
        - objectName: postgresql-password
          key: postgresql-password
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:250566739804:secret:rds!db-418f1dcc-779f-40ee-a169-7ecf6787bdd9-1J8Dfo"
        objectType: "secretsmanager"
        jmesPath:
            - path: "password"
              objectAlias: "postgresql-password"
