apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'public.ecr.aws/karpenter'
      chart: karpenter
      targetRevision: v0.6.0
      helm:
        valueFiles:
          - $valuesRepo/kubernetes/values/karpenter-values.yaml
    - repoURL: 'https://github.com/tjrohweder/lab-k8s.git'
      targetRevision: HEAD
      ref: valuesRepo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tjrohweder/lab-k8s.git'
    targetRevision: HEAD
    path: kubernetes/manifests
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
